# Generated by Django 6.0 on 2025-12-22 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='api_project_created_cff6f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('indicator', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default=10)),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=20, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Compliant', 'Compliant'), ('Non-Compliant', 'Non-Compliant'), ('Not Applicable', 'Not Applicable')], default='Not Started', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('form_schema', models.JSONField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('ai_categorization', models.CharField(blank=True, choices=[('ai_fully_manageable', 'AI Fully Manageable'), ('ai_assisted', 'AI Assisted'), ('manual', 'Manual')], max_length=30, null=True)),
                ('is_ai_completed', models.BooleanField(default=False)),
                ('is_human_verified', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.project')),
            ],
            options={
                'ordering': ['section', 'standard'],
            },
        ),
        migrations.CreateModel(
            name='DriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('root_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_config', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('certificate', 'Certificate'), ('note', 'Note'), ('link', 'Link')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_view_link', models.CharField(blank=True, max_length=500, null=True)),
                ('sync_status', models.CharField(blank=True, choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error')], max_length=20, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.indicator')),
            ],
            options={
                'ordering': ['-date_uploaded'],
                'indexes': [models.Index(fields=['indicator'], name='api_evidenc_indicat_15b1dc_idx'), models.Index(fields=['type'], name='api_evidenc_type_6ae0aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['project'], name='api_indicat_project_8fdbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['status'], name='api_indicat_status_f76131_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['frequency'], name='api_indicat_frequen_cc7680_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['ai_categorization'], name='api_indicat_ai_cate_a7661d_idx'),
        ),
    ]
