# Generated by Django 6.0 on 2026-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_evidence_system_phase6'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidence',
            new_name='api_evidenc_drive_f_75322a_idx',
            old_name='api_evidenc_drive_f_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='evidence',
            new_name='api_evidenc_review__9ce442_idx',
            old_name='api_evidenc_review__idx',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
