# Generated by Django 6.0 on 2026-01-31 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_api_evidenc_drive_f_123abc_idx_api_evidenc_drive_f_75322a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('expected_evidence_count', models.IntegerField(default=1)),
                ('actual_evidence_count', models.IntegerField(default=0)),
                ('is_compliant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='FrequencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_compliant', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_key',
            field=models.CharField(blank=True, db_index=True, help_text='Hash for idempotent imports', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='schedule_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], default='one_time', max_length=20),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['indicator_key'], name='api_indicat_indicat_372b01_idx'),
        ),
        migrations.AddField(
            model_name='evidenceperiod',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_periods', to='api.indicator'),
        ),
        migrations.AddField(
            model_name='frequencylog',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_logs', to='api.indicator'),
        ),
        migrations.AddField(
            model_name='frequencylog',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='evidenceperiod',
            unique_together={('indicator', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='frequencylog',
            unique_together={('indicator', 'period_start', 'period_end')},
        ),
    ]
